### ISSUE TITLE
Unify Frontend of PersonalAnalytics (using Electron)

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#205]
### Idea
- the backend (i.e. data trackers) for the Windows and Mac version are separate (and stay that for now)
- since the visualizations are already produced using JavaScript/D3 and visualized in a web wrapper, we'd like to unify the code of the UI to only have one codebase
- currently, the idea is to build an Electron app

### Tasks
- [ ] Unify data access (API) on Mac (cc @csatterfield)
- [ ] think about useful abstraction
- [ ] create Electron-app 
- [ ] migrate visualizations/views
- [ ] do the same for the other windows (e.g. Settings, FirstStartScreen, Credits)

**Comment by casaout** [comment]
Closing as reported for legacy version of PersonalAnalytics.
