### ISSUE TITLE
Create Multi-Platform App

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#271]
- [x] multi-platform app that runs on Windows and macOS
  - [x] name: `PersonalAnalytics`
  - [x] technology: using the newest electron-version, written in typescript, client-side framework can be Vue.js or React)
  - [x] whenever an accent color is selected, the PA-blue should be used `#007ACC`
- [x] good, automated install and update-mechanism (reuse from AwarenessBar, details `tbd`)
  - needs static link, similar to how it's done with vercel
- [x] automated build pipeline using Github Actions (could re-use system from FT or use better one;)
  - [x] also consider #273
  - [ ] `tbd` separate build for arm-based processors on macOS?
- [x] data collection using sqlite #275
- [x] client logs shall be stored in a `logs`-folder (ideally similar to FT)
- [x] app and tasktray icon #276
