### ISSUE TITLE
About-Page

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#272]
In the tasktray/menubar-icon, add a menu point "About" that opens a pop-up with the following information:

- [x] Study Info
   - [x] subject ID 
   - [x] study description  (details: #273)
   - [x] Link to study  (details: #273)
   - [x] researcher contact info  (details: #273)
- [x] Monitoring Tool Info
  - [x] app version number
  - [x] short summary of PA `tbd`
  - [x] link to [PersonalAnalytics](https://github.com/HASEL-UZH/PersonalAnalytics)
  - [x] link to privacy policy (details: #273; or [ours](https://github.com/HASEL-UZH/PersonalAnalytics/blob/dev-am/documentation/PRIVACY.md))
  - [x] show names of currently running data trackers #274
  - [x] Contact: Andre Meyer (with Email), Sebastian Richner (with email, unless you don't want to) and UZH + HASEL logo
