### ISSUE TITLE
Add Data Trackers

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#274]
While we (and others) might want to add additional trackers in the future, we want to focus on the following two initially:

- https://github.com/HASEL-UZH/PA.WindowsActivityTracker/tree/main/typescript
- https://github.com/HASEL-UZH/PA.UserInputTracker/tree/main/typescript

Please create the setup in a way to make this extensible with other trackers and easy to enable/disable them (if necessary). We can also discuss this further. `tbd`

If easily possible, it'd be nice to know at run-time which data trackers are currently running and show them in the about page. 

Tasks:
- [x] Add WindowsActivityTracker
- [x] Add UserInputTracker
- [x] Consider power management (logout, restart, signout) to start/stop trackers
- [x] `update library & observe` For WindowsActivityTracker (and depending on how we implement the build for macOS ARM procesors #271): check if this is an issue we need to fix: https://github.com/HASEL-UZH/PA.WindowsActivityTracker/issues/14
- [x] `update library & observe` For UserInputTracker: find a better IOhook library https://github.com/HASEL-UZH/PA.UserInputTracker/issues/4 (also that one ideally should be better compatible with macOS ARM processors)
- [x] Check if bug still exists https://github.com/HASEL-UZH/PA.WindowsActivityTracker/issues/8
- [ ] `P2` context menu option to pause/continue trackers (+ reminder to not forget to continue)

**Comment by casaout** [comment]
> Does it make sense to create a separate tracker for tracking in-IDE things (like the tasksnap VScode extension)?

yes, i would treat this as a separate tracker; where the onboarding guide can (if enabled) help to install it. 
In your case, it might make sense to create a fork and then create the connection between the VSCode extension and PA.
