### ISSUE TITLE
Experience Sampling Component

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#279]
Similar to today's version of PersonalAnalytics, we want to introduce a simple pop-up asking the user one question in a predefined interval:

- [x] Question (defined in the study-settings #273)
- [x] Response options are on a 7-point Likert-scale (with labels defined in the study-settings #273)
- [x] responses should store timestamp, question and response (in the table defined in #275)
- [ ] timing as defined in the study settings (#273): `experience sampling interval` and `experience sampling randomization`  (e.g. once a day, random every 8-12 hours)
- [x] Pop-up that opens in the foreground and closes as soon as the response is selected
- [ ] `P2` ability to postpone the question

Inspiration
<img width="377" alt="image" src="https://github.com/HASEL-UZH/PersonalAnalytics/assets/5212692/b3999e7c-1165-444e-9367-94f2b39be5df">

**Comment by SRichner** [comment]
Similar to master project:
- title: icon, `study name: Self-Report`:
![image](https://github.com/HASEL-UZH/PersonalAnalytics/assets/14821076/3211e290-06a8-4337-99f2-0d2614ed35a5)
