### ISSUE TITLE
Create Upload Option to Data Donation Lab

### ISSUE THREAD

**Issue by casaout** [HASEL-UZH/PersonalAnalytics#324]
## Todos
- [x] Create first version
- [x] Deploy first version for (internal) testing
- [ ] testing `in progress`
- [ ] test data analysis (from exported and downloaded project)
- [ ] Create documentation on GH/readme (enabling, setting up DDL-upload, analyzing exported data)
- [x] `improvement` @royru suggested to use fetch() instead of `axios` to not have to add a separate package (possibly, we can also remove the `form-data` package) [this is also important as Axios is vulnerable to DoS attacks (CVE-2025-58754)]
- [x]  `improvement` provide secrets via API-request instead of via GH Secrets

## Notes from second Meeting on 24.10.2024
- Derzeit: Refactoring, anschliessend: APIs 
- Möglichkeit
  - 1: heute schon, einfach Projekt-Uploadseite 
  - 2: integrierter Upload  (möglicherweise bei Schritt gerade vor Abspeichern in DB)
    - Export in JSON/CSV in ZIP-FIle 
    - Schema von irgendwo übernehmen  (solange Input stabil bleibt, leicht)
    - Projekt kopieren
  - 3: auch noch Infos wie Kontakt, Privacy Policy, usw mitgeben  
-  Nico meldet sich
